server:
  port: 8888
  servlet:
    context-path: /jzl

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: develop
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:/mapper/*.xml
